version: '3'
services:
    brackets:
        container_name: brackets-server
        build: .
        working_dir: /usr/share/nginx/html
        volumes:
            - ./.:/usr/share/nginx/html:delegated
        ports:
            - 82:80
